=== davidmegli/Snap4Simulator/src/simulation_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "simulation": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "cycles": {
            "type": "integer"
          },
          "timeStep": {
            "type": "integer"
          },
          "vehicleInjectionRate": {
            "type": "integer"
          },
          "sectorLength": {
            "type": "integer"
          },
          "log": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "cycles",
          "timeStep",
          "vehicleInjectionRate",
          "sectorLength",
          "log"
        ]
      },
      "vehicles": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "length": {
                "type": "number"
              },
              "initialPosition": {
                "type": "number"
              },
              "initialSpeed": {
                "type": "number"
              },
              "initialAcceleration": {
                "type": "number"
              },
              "maxSpeed": {
                "type": "number"
              },
              "maxAcceleration": {
                "type": "number"
              },
              "creationTime": {
                "type": "integer"
              },
              "sigma": {
                "type": "number"
              },
              "reactionTime": {
                "type": "number"
              },
              "reactionTimeAtSemaphore": {
                "type": "number"
              },
              "dampingFactor": {
                "type": "number"
              }
            },
            "required": [
              "length",
              "initialPosition",
              "initialSpeed",
              "initialAcceleration",
              "maxSpeed",
              "maxAcceleration",
              "creationTime",
              "sigma",
              "reactionTime",
              "reactionTimeAtSemaphore",
              "dampingFactor"
            ]
          }
        ]
      },
      "roads": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "length": {
                "type": "integer"
              },
              "vehicleDistance": {
                "type": "integer"
              },
              "speedLimit": {
                "type": "integer"
              },
              "isStartingRoad": {
                "type": "boolean"
              },
              "shape": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  },
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "length",
              "vehicleDistance",
              "speedLimit",
              "isStartingRoad",
              "shape"
            ]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "length": {
                "type": "integer"
              },
              "vehicleDistance": {
                "type": "integer"
              },
              "speedLimit": {
                "type": "integer"
              },
              "isStartingRoad": {
                "type": "boolean"
              },
              "shape": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  },
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "length",
              "vehicleDistance",
              "speedLimit",
              "isStartingRoad",
              "shape"
            ]
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "length": {
                "type": "integer"
              },
              "vehicleDistance": {
                "type": "integer"
              },
              "speedLimit": {
                "type": "integer"
              },
              "isStartingRoad": {
                "type": "boolean"
              },
              "shape": {
                "type": "array",
                "items": [
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  },
                  {
                    "type": "object",
                    "properties": {
                      "x": {
                        "type": "number"
                      },
                      "y": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "x",
                      "y"
                    ]
                  }
                ]
              }
            },
            "required": [
              "id",
              "length",
              "vehicleDistance",
              "speedLimit",
              "isStartingRoad",
              "shape"
            ]
          }
        ]
      },
      "semaphores": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "position": {
                "type": "integer"
              },
              "greenLight": {
                "type": "integer"
              },
              "yellowLight": {
                "type": "integer"
              },
              "redLight": {
                "type": "integer"
              },
              "startTime": {
                "type": "integer"
              },
              "road": {
                "type": "integer"
              }
            },
            "required": [
              "id",
              "position",
              "greenLight",
              "yellowLight",
              "redLight",
              "startTime",
              "road"
            ]
          }
        ]
      },
      "intersections": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "inRoads": {
                "type": "array",
                "items": [
                  {
                    "type": "integer"
                  }
                ]
              },
              "outRoads": {
                "type": "array",
                "items": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "integer"
                  }
                ]
              },
              "outFluxes": {
                "type": "array",
                "items": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ]
              }
            },
            "required": [
              "id",
              "inRoads",
              "outRoads",
              "outFluxes"
            ]
          }
        ]
      }
    },
    "required": [
      "simulation",
      "vehicles",
      "roads",
      "semaphores",
      "intersections"
    ]
  }

=== davidmegli/Snap4Simulator/src/simulation.json
{
    "simulation": {
        "name": "simulation",
        "cycles": 600,
        "timeStep": 1,
        "vehicleInjectionRate": 1,
        "sectorLength": 100,
        "log": false
    },
    "vehicles": [
        {
            "length": 5.0,
            "initialPosition": 0.0,
            "initialSpeed": 7.0,
            "initialAcceleration": 0.0,
            "maxSpeed": 7.0,
            "maxAcceleration": 4.0,
            "creationTime": 0,
            "sigma": 0.0,
            "reactionTime": 1.0,
            "reactionTimeAtSemaphore": 1.0,
            "dampingFactor": 0.18
        } ],
    "roads": [
        {
            "id": 1,
            "length": 1000,
            "vehicleDistance": 1,
            "speedLimit": 7,
            "isStartingRoad": true,
            "shape": [
                {
                    "x": 0.0,
                    "y": 0.0
                },
                {
                    "x": 1000.0,
                    "y": 0.0
                }
            ]
        },
        {
            "id": 2,
            "length": 500,
            "vehicleDistance": 1,
            "speedLimit": 7,
            "isStartingRoad": false,
            "shape": [
                {
                    "x": 1000.0,
                    "y": 0.0
                },
                {
                    "x": 1353.55339,
                    "y": 353.55339
                }
            ]
        },
        {
            "id": 3,
            "length": 500,
            "vehicleDistance": 1,
            "speedLimit": 7,
            "isStartingRoad": false,
            "shape": [
                {
                    "x": 1000.0,
                    "y": 0.0
                },
                {
                    "x": 1353.55339,
                    "y": -353.55339
                }
            ]
        }
    ],
    "semaphores": [
        {
            "id": 1,
            "position": 800,
            "greenLight": 40,
            "yellowLight": 0,
            "redLight": 20,
            "startTime": 0,
            "road": 1
        }
    ],
    "intersections": [
        {
            "id": 1,
            "inRoads": [1],
            "outRoads": [2,3],
            "outFluxes": [0.5,0.5]
        }
    ]
}
